version: '3'
services:
   dynamodb:
      #build: .
      image: localstack/localstack:latest
      container_name: dynamo-db
      ports:
      - "4569"
      
   pokedex:
      build: ../pokedex
      ports:
      - "8080"
      environment: 
      - DYNAMODB_URL=http://dynamo-db:4569
      links:
      - dynamodb
      